baseURL = "https://www.zrzka.dev/"
languageCode = "en-us"
title = "Robert Vojta (ğ’µğ“‡ğ“ğ“€ğ’¶)"
description = "foo"
googleAnalytics = "UA-110967877-1"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post = "/:title"
pages = "/:title"
