baseURL = "https://www.zrzka.org/"
languageCode = "en-us"
title = "Robert Vojta (ğ’µğ“‡ğ“ğ“€ğ’¶)"
description = "foo"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post = "/:title"
pages = "/:title"

[markup.goldmark.renderer]
unsafe= true

[minify]
disableHTML = true

[minify.tdewolff.html]
keepQuotes = true
keepComments = true
keepEndTags = true
keepWhitespace = true
